# pytorch笔记

In [1]:
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 9.5510e-39],
        [1.0561e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6544, 0.6843, 0.2129],
        [0.8552, 0.1428, 0.5478],
        [0.1186, 0.2113, 0.9189],
        [0.2549, 0.9646, 0.1883],
        [0.1778, 0.3651, 0.9270]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [9]:
x = torch.ones(5, 3, dtype= torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

7. 从已有的张量创建相同维度的新张量，并且重新定义类型为float

In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.5181,  1.2922, -0.0195],
        [-0.0924, -1.3450, -0.1408],
        [ 1.4932,  0.2695,  0.2548],
        [ 0.0611,  0.0362,  0.2906],
        [ 1.1185,  0.1919, -0.0606]])


In [15]:
print(x.size())

torch.Size([5, 3])


In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2221,  2.1032,  0.3924],
        [ 0.7521, -0.6409,  0.5700],
        [ 2.1550,  0.8199,  1.2192],
        [ 0.7655,  0.9733,  0.9894],
        [ 1.6775,  1.1368,  0.6351]])


In [17]:
# 方法二
print(torch.add(x, y))

tensor([[-0.2221,  2.1032,  0.3924],
        [ 0.7521, -0.6409,  0.5700],
        [ 2.1550,  0.8199,  1.2192],
        [ 0.7655,  0.9733,  0.9894],
        [ 1.6775,  1.1368,  0.6351]])


In [18]:
# 方法三
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.2221,  2.1032,  0.3924],
        [ 0.7521, -0.6409,  0.5700],
        [ 2.1550,  0.8199,  1.2192],
        [ 0.7655,  0.9733,  0.9894],
        [ 1.6775,  1.1368,  0.6351]])


In [19]:
# 方法四
y.add_(x)
print(y)

tensor([[-0.2221,  2.1032,  0.3924],
        [ 0.7521, -0.6409,  0.5700],
        [ 2.1550,  0.8199,  1.2192],
        [ 0.7655,  0.9733,  0.9894],
        [ 1.6775,  1.1368,  0.6351]])


In [20]:
print(x[:, 1])

tensor([ 1.2922, -1.3450,  0.2695,  0.0362,  0.1919])


In [23]:
x = torch.randn(4, 4)
y = x.view(16)
print(x)
print(y)
print(x.size(),y.size())

tensor([[ 0.1045, -0.9391,  0.4311,  1.1792],
        [-0.2309, -1.3718, -1.1838, -0.1116],
        [ 1.3181, -1.3178,  1.5650, -0.0943],
        [ 0.9662,  1.0902,  0.8612, -1.0976]])
tensor([ 0.1045, -0.9391,  0.4311,  1.1792, -0.2309, -1.3718, -1.1838, -0.1116,
         1.3181, -1.3178,  1.5650, -0.0943,  0.9662,  1.0902,  0.8612, -1.0976])
torch.Size([4, 4]) torch.Size([16])


In [27]:
x = torch.randn(1)
print(x)
print(x.item())
print()
x = torch.randn(2)
print(x)
print(x[0])
print(x[0].item())

tensor([0.4400])
0.4399701952934265

tensor([1.8260, 1.7558])
tensor(1.8260)
1.8260414600372314


 # Numpy的操作

In [31]:
# 将张量装换成numpy数组

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# 2 自动微分
## 2.1 张量的自动微分
### 18. 新建一个张量，并设置requires_grad=True

In [40]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


### 19.对张量进行任意操作（y = x + 2）

In [41]:
y = x + 2
print(y)
print(y.grad_fn) # y就多了一个AddBackward

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


### 20.再对y进行任意操作

In [42]:
z = y * y * 3
out = z.mean()

print(z) # z多了MulBackward
print(out) # out多了MeanBackward

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


## 2.2 梯度
### 21.对out进行反向传播

In [43]:
out.backward()

### 22.打印梯度d(out)/dx

In [44]:
print(x.grad) #out=0.25*Σ3(x+2)^2

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### 23.创建一个结果为矢量的计算过程（y=x*2^n）

In [45]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-330.5654, 1177.2318,  968.1824], grad_fn=<MulBackward0>)


广播机制


In [46]:
# 示例1：相同形状的张量总是可广播的，因为总能满足以上规则。
x = torch.empty(5, 7, 3)
y = torch.empty(5, 7, 3)
x + y

tensor([[[ 2.5348e-38,  1.1314e-37,         nan],
         [        nan,  2.1466e+29,  6.7111e+22],
         [-1.7672e+30,  2.6817e-38,  2.5715e-38],
         [ 1.4277e+04,  2.7376e+20,  4.5448e+30],
         [ 1.6877e+25,  1.7612e+19,  3.2501e-39],
         [ 1.0194e-38,  9.3674e-39,  5.4183e-39],
         [ 9.2754e-39,  4.5706e-35,  2.6585e+36]],

        [[-2.0470e+38,  2.4137e+12,  7.2245e+30],
         [ 1.1563e+19,  5.4063e+19,  2.0564e+12],
         [ 2.5353e+30, -1.8671e+38,  7.8156e+08],
         [ 2.7148e+33,  4.6164e+24,  5.8011e+08],
         [ 1.6486e+11,  1.6745e+35,  6.1393e+28],
         [ 7.1441e+31,  5.5115e-11,  7.2387e+31],
         [ 9.7704e-39,  9.2754e-39,  1.0561e-38]],

        [[ 1.1388e-38,  1.1020e-38, -4.5700e-35],
         [ 2.6585e+36,  2.5435e+30,  3.8832e+25],
         [ 1.2134e+22,  2.7086e+36,  4.1647e+31],
         [-3.8160e-37,  2.7086e+36,  1.0759e+37],
         [ 4.9938e+36,  2.6623e+30,  3.9409e+25],
         [-3.7758e-37,  4.1353e+31,  2.8332e+3

In [51]:
# 示例2：不可广播（ a 不满足第一条规则）。
a = torch.empty((0,1))
b = torch.empty(2, 2)
(a+b).size()

RuntimeError: The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 0

In [50]:
# 示例3：m 和 n 可广播：
m = torch.empty(5, 3, 4, 1)
n = torch.empty(   3, 1, 1)
# 倒数第一个维度：两者的尺寸均为1
# 倒数第二个维度：n尺寸为1
# 倒数第三个维度：两者尺寸相同
# 倒数第四个维度：n该维度不存在
(m+n).size()

torch.Size([5, 3, 4, 1])

In [52]:
# 示例4：不可广播，因为倒数第三个维度：2 != 3
p = torch.empty(5, 2, 4, 1)
q = torch.empty(   3, 1, 1)
p+q

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [54]:
# 示例5：可广播
c = torch.empty(5, 1, 4, 1)
d = torch.empty(   3, 1, 1)
print((c + d).size())  # torch.Size([5, 3, 4, 1])


# 示例6：可广播
f = torch.empty(      1)
g = torch.empty(3, 1, 7)
print((f + g).size())  # torch.Size([3, 1, 7])

# 示例7：不可广播
o = torch.empty(5, 2, 4, 1)
u = torch.empty(   3, 1, 1)
(o + u).size()

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [62]:
x = torch.zeros(1,1)
y = torch.ones(1,1)
before = x
x +=y
print(before==x)

tensor([[True]])


In [64]:
x = torch.zeros(1,1)
y = torch.ones(1,1)
before = x
x = x + y
print(before==x)

tensor([[False]])


In [78]:
x = torch.arange(4, dtype=torch.float32).reshape(4,1)
y = torch.ones(4, dtype = torch.float32).reshape(4,1)
x,x.T,torch.mm(x.T,y)

(tensor([[0.],
         [1.],
         [2.],
         [3.]]),
 tensor([[0., 1., 2., 3.]]),
 tensor([[6.]]))

In [84]:
A = torch.arange(20, dtype= torch.float32).reshape(4,5)
A,A.sum(axis=1)


(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([10., 35., 60., 85.]))